# -*- coding: utf-8 -*-
"""AulaDatasets .ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Pu7B0aQvrn7EcP4eHnifACDfkTJyZ5BI
"""

import pandas as pd

from sklearn.datasets import load_iris

dataset = load_iris()

dataset

x = dataset['data']
y = dataset['target']

from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.3, random_state = 42)

!pip install plotly

import plotly.express as px

df = px.data.iris()
fig = px.scatter_3d(df,                #dataset
                    x='sepal_length',  #coluna x
                    y='sepal_width',   #coluna y
                    z='petal_width',   #coluna z
                    color='species')   #colorir
fig.show()

from sklearn.tree import DecisionTreeClassifier

clf = DecisionTreeClassifier().fit(x_train, y_train)

from sklearn.tree import plot_tree
plot_tree(clf);

from sklearn.metrics import plot_confusion_matrix

perdicoes = clf.predict(x_test)

plot_confusion_matrix(clf, x_test, y_test)

